### ISSUE TITLE
role base permission

### ISSUE THREAD

**Issue by kaktoosii** [VahidN/BlazorWasmDynamicPermissions#1]
سلام چطور میشه به جای اعطای دسترسی ها به کاربران به نقش ها داد

**Comment by VahidN** [comment]
- روش فعلي كه انعطاف پذيري بيشتري دارد و پوياتر هست.
- نياز خواهيد داشت يك قسمت انتساب نقش به كاربر اضافه كنيد و بعد هم انتساب صفحه يا اكشن متد به نقش. من قصد انجام چنين تغييراتي را ندارم.
