### ISSUE TITLE
خطای هنگام بیلد  پروژه

### ISSUE THREAD

**Issue by saeed-m** [VahidN/BlazorWasmDynamicPermissions#2]
در ویژول استدیو 2022 ورژن 17.12.3 هنگام build با خطای زیر که این یک نمونه از آن ها ست بر خورد می شود. تعداد خطا ها 60 مورد میباشد
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CA1515	Because an application's API isn't typically referenced from outside the assembly, types can be made internal (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1515)	BlazorWasmDynamicPermissions.Client	E:\BlazorWasmDynamicPermissions-main\src\Client\ClientAuthorization\Components\DropdownMenuItem.cs	3	
در صورت امکان این پروژه رو به دانت 9 ارتقاع دهید.ممنون

**Comment by VahidN** [comment]
پروژه به دات‌نت 9 ارتقاء داده شد.
